package Frontend;

import Backend.DataTypes.Fair;
import Backend.DataTypes.Product;
import Backend.DataTypes.Sale;
import Backend.DataTypes.Store;
import Backend.ManagerClasses.FairManager;
import Backend.ManagerClasses.SalesManager;
import Backend.ManagerClasses.StoreManager;
import Backend.Utility.DB;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Panel;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class FairManagerScreen extends javax.swing.JFrame {

    private JPanel current_button;
    private JLabel current_label;
    
    private StoreManager sm;
    private FairManager fm;
    private SalesManager sales_manager;
    
    private void changeBackgroundColor(JPanel newP, JPanel oldP,JLabel newL,JLabel oldL){
        Color off = new Color(65,67,106);
        Color on = new Color(254,150,103);
        Color label_off = new Color(254,150,103);
        Color label_on = new Color(255,255,255);
        newP.setBackground(on);
        oldP.setBackground(off);
        newL.setForeground(label_on);
        oldL.setForeground(label_off);
    }    
    
    
    
    
    
    
    public FairManagerScreen() throws ClassNotFoundException, SQLException{
        
        this.sales_manager = new SalesManager();
        this.sm = new StoreManager();
        this.fm = new FairManager();
        
        initComponents();
        //setting up titles and Images 
        this.setTitle("Fair Management");
        ImageIcon main = new ImageIcon("src\\main\\resources\\login_screen Images\\Ferris Wheel 64x.png");
        this.setIconImage(main.getImage());    
        
        
        current_button = entrance_button_panel;
        current_label = entrance_management_label;
        initialiseTicketSalesTable(Ticket_sales_table);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent_panel = new javax.swing.JPanel();
        entrance_management_panel = new javax.swing.JPanel();
        num_people_spinner = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        sell_tickets_button = new javax.swing.JButton();
        ticket_total_price_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ticket_sales_table = new javax.swing.JTable();
        user_management_screen_label = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        stores_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        stores_of_fair_table = new javax.swing.JTable();
        user_management_screen_label1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fair_statistics_panel = new javax.swing.JPanel();
        total_profit_of_fair = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        most_popular_store_field = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        least_popular_store_field = new javax.swing.JTextField();
        user_management_screen_label2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        panel_middle = new javax.swing.JPanel();
        panel_left = new javax.swing.JPanel();
        entrance_button_panel = new javax.swing.JPanel();
        entrance_management_label = new javax.swing.JLabel();
        stores_button_panel = new javax.swing.JPanel();
        stores_label = new javax.swing.JLabel();
        fair_statistics_button_panel = new javax.swing.JPanel();
        fair_statistics_label = new javax.swing.JLabel();
        my_fair_lady_label = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();
        fair_name_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        parent_panel.setBackground(new java.awt.Color(246, 70, 104));
        parent_panel.setLayout(new java.awt.CardLayout());

        entrance_management_panel.setBackground(new java.awt.Color(246, 70, 104));

        num_people_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                num_people_spinnerStateChanged(evt);
            }
        });
        num_people_spinner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num_people_spinnerMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(254, 150, 103));
        jLabel20.setText("Total:");

        jLabel21.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(254, 150, 103));
        jLabel21.setText("People:");

        sell_tickets_button.setText("SELL TICKETS");
        sell_tickets_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_tickets_buttonActionPerformed(evt);
            }
        });

        Ticket_sales_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Day", "Tickets Sold", "Total"
            }
        ));
        Ticket_sales_table.setEnabled(false);
        jScrollPane1.setViewportView(Ticket_sales_table);

        user_management_screen_label.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        user_management_screen_label.setForeground(new java.awt.Color(254, 150, 103));
        user_management_screen_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_management_screen_label.setText("Tickets");

        jSeparator3.setForeground(new java.awt.Color(254, 150, 103));

        javax.swing.GroupLayout entrance_management_panelLayout = new javax.swing.GroupLayout(entrance_management_panel);
        entrance_management_panel.setLayout(entrance_management_panelLayout);
        entrance_management_panelLayout.setHorizontalGroup(
            entrance_management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entrance_management_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(entrance_management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sell_tickets_button, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(entrance_management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator3)
                        .addComponent(user_management_screen_label, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                    .addGroup(entrance_management_panelLayout.createSequentialGroup()
                        .addGroup(entrance_management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(entrance_management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ticket_total_price_field, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_people_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        entrance_management_panelLayout.setVerticalGroup(
            entrance_management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entrance_management_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user_management_screen_label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(entrance_management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entrance_management_panelLayout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(entrance_management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_people_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(entrance_management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ticket_total_price_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(268, 268, 268)
                        .addComponent(sell_tickets_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        parent_panel.add(entrance_management_panel, "card2");

        stores_panel.setBackground(new java.awt.Color(246, 70, 104));

        stores_of_fair_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Products", "Total Cost", "Income", "Profit", "Number of Customers", "Category"
            }
        ));
        jScrollPane3.setViewportView(stores_of_fair_table);

        user_management_screen_label1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        user_management_screen_label1.setForeground(new java.awt.Color(254, 150, 103));
        user_management_screen_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_management_screen_label1.setText("Stores");

        jSeparator1.setForeground(new java.awt.Color(254, 150, 103));

        javax.swing.GroupLayout stores_panelLayout = new javax.swing.GroupLayout(stores_panel);
        stores_panel.setLayout(stores_panelLayout);
        stores_panelLayout.setHorizontalGroup(
            stores_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stores_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(stores_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stores_panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(stores_panelLayout.createSequentialGroup()
                        .addGroup(stores_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_management_screen_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        stores_panelLayout.setVerticalGroup(
            stores_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stores_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user_management_screen_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        parent_panel.add(stores_panel, "card3");

        fair_statistics_panel.setBackground(new java.awt.Color(246, 70, 104));

        jLabel12.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 150, 103));
        jLabel12.setText("Overall Income");

        jLabel14.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(254, 150, 103));
        jLabel14.setText("Least Popular Store");

        jLabel26.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(254, 150, 103));
        jLabel26.setText("Most Popular Store");

        user_management_screen_label2.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        user_management_screen_label2.setForeground(new java.awt.Color(254, 150, 103));
        user_management_screen_label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_management_screen_label2.setText("Statistics");

        jSeparator2.setForeground(new java.awt.Color(254, 150, 103));

        javax.swing.GroupLayout fair_statistics_panelLayout = new javax.swing.GroupLayout(fair_statistics_panel);
        fair_statistics_panel.setLayout(fair_statistics_panelLayout);
        fair_statistics_panelLayout.setHorizontalGroup(
            fair_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fair_statistics_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(fair_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fair_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(user_management_screen_label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                    .addGroup(fair_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(fair_statistics_panelLayout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(total_profit_of_fair, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(fair_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(fair_statistics_panelLayout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(most_popular_store_field, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fair_statistics_panelLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(least_popular_store_field, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 503, Short.MAX_VALUE))
        );
        fair_statistics_panelLayout.setVerticalGroup(
            fair_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fair_statistics_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user_management_screen_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fair_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(most_popular_store_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(fair_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(least_popular_store_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addGroup(fair_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_profit_of_fair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );

        parent_panel.add(fair_statistics_panel, "card4");

        panel_middle.setBackground(new java.awt.Color(65, 67, 106));
        panel_middle.setForeground(new java.awt.Color(65, 67, 106));

        javax.swing.GroupLayout panel_middleLayout = new javax.swing.GroupLayout(panel_middle);
        panel_middle.setLayout(panel_middleLayout);
        panel_middleLayout.setHorizontalGroup(
            panel_middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        panel_middleLayout.setVerticalGroup(
            panel_middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_left.setBackground(new java.awt.Color(152, 64, 99));

        entrance_button_panel.setBackground(new java.awt.Color(254, 150, 103));
        entrance_button_panel.setPreferredSize(new java.awt.Dimension(100, 50));
        entrance_button_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrance_button_panelMouseClicked(evt);
            }
        });

        entrance_management_label.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        entrance_management_label.setForeground(new java.awt.Color(255, 255, 255));
        entrance_management_label.setText("ENTRANCE MANAGEMENT");

        javax.swing.GroupLayout entrance_button_panelLayout = new javax.swing.GroupLayout(entrance_button_panel);
        entrance_button_panel.setLayout(entrance_button_panelLayout);
        entrance_button_panelLayout.setHorizontalGroup(
            entrance_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entrance_button_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entrance_management_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        entrance_button_panelLayout.setVerticalGroup(
            entrance_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entrance_button_panelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(entrance_management_label)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        stores_button_panel.setBackground(new java.awt.Color(65, 67, 106));
        stores_button_panel.setPreferredSize(new java.awt.Dimension(100, 50));
        stores_button_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stores_button_panelMouseClicked(evt);
            }
        });

        stores_label.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        stores_label.setForeground(new java.awt.Color(254, 150, 103));
        stores_label.setText("STORES");

        javax.swing.GroupLayout stores_button_panelLayout = new javax.swing.GroupLayout(stores_button_panel);
        stores_button_panel.setLayout(stores_button_panelLayout);
        stores_button_panelLayout.setHorizontalGroup(
            stores_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
            .addGroup(stores_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(stores_button_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(stores_label)
                    .addContainerGap(240, Short.MAX_VALUE)))
        );
        stores_button_panelLayout.setVerticalGroup(
            stores_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(stores_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(stores_button_panelLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(stores_label)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        fair_statistics_button_panel.setBackground(new java.awt.Color(65, 67, 106));
        fair_statistics_button_panel.setPreferredSize(new java.awt.Dimension(100, 50));
        fair_statistics_button_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fair_statistics_button_panelMouseClicked(evt);
            }
        });

        fair_statistics_label.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        fair_statistics_label.setForeground(new java.awt.Color(254, 150, 103));
        fair_statistics_label.setText("FAIR STATISTICS");

        javax.swing.GroupLayout fair_statistics_button_panelLayout = new javax.swing.GroupLayout(fair_statistics_button_panel);
        fair_statistics_button_panel.setLayout(fair_statistics_button_panelLayout);
        fair_statistics_button_panelLayout.setHorizontalGroup(
            fair_statistics_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
            .addGroup(fair_statistics_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fair_statistics_button_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(fair_statistics_label)
                    .addContainerGap(244, Short.MAX_VALUE)))
        );
        fair_statistics_button_panelLayout.setVerticalGroup(
            fair_statistics_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(fair_statistics_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fair_statistics_button_panelLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(fair_statistics_label)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        try{
            Font font = Font.createFont(Font.TRUETYPE_FONT,
                new File("AmbarPearlPersonalUse-0nBz.ttf"));
            Font bold = font.deriveFont(Font.BOLD, 12);
            Font plain = font.deriveFont(Font.PLAIN, 24);
            my_fair_lady_label.setForeground(new java.awt.Color(254, 150, 103));
            my_fair_lady_label.setFont(plain);
            my_fair_lady_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            my_fair_lady_label.setText("MyFairLady");
            my_fair_lady_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        } catch (FontFormatException | IOException e){
            e.printStackTrace();
        }

        back_button.setText("BACK");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        fair_name_label.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        fair_name_label.setForeground(new java.awt.Color(255, 255, 255));
        fair_name_label.setText("FAIR NAME GOES HERE");

        javax.swing.GroupLayout panel_leftLayout = new javax.swing.GroupLayout(panel_left);
        panel_left.setLayout(panel_leftLayout);
        panel_leftLayout.setHorizontalGroup(
            panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entrance_button_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(stores_button_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(fair_statistics_button_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(my_fair_lady_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_leftLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_leftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fair_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_leftLayout.setVerticalGroup(
            panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_leftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fair_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entrance_button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stores_button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fair_statistics_button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(my_fair_lady_label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_middle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(parent_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(parent_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_middle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fair_statistics_button_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fair_statistics_button_panelMouseClicked
        
        try {
            //changes colour of panels and labels to show a tab is selected
            changeBackgroundColor(fair_statistics_button_panel, current_button,fair_statistics_label,current_label);
            current_button = fair_statistics_button_panel;
            current_label = fair_statistics_label;
            
            most_popular_store_field.setText(fm.getMostPopularStore(fair_name_label.getText()));
            least_popular_store_field.setText(fm.getMostPopularStore(fair_name_label.getText()));
            total_profit_of_fair.setText(Double.toString(fm.getFairProfit(fair_name_label.getText())));
            
            
            //changes the card layout to bring up the dashboard panel
            parent_panel.removeAll();
            parent_panel.add(fair_statistics_panel);
            parent_panel.repaint();
            parent_panel.revalidate();
        } catch (SQLException ex) {
            Logger.getLogger(FairManagerScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fair_statistics_button_panelMouseClicked

    private void stores_button_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stores_button_panelMouseClicked
        
        //changes colour of panels and labels to show a tab is selected
        changeBackgroundColor(stores_button_panel, current_button,stores_label,current_label);
        current_button = stores_button_panel;
        current_label = stores_label;
        try {
            initialiseStoresOfFairTable(stores_of_fair_table);
        } catch (SQLException ex) {
            Logger.getLogger(FairManagerScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        //changes the card layout to bring up the dashboard panel
        parent_panel.removeAll();
        parent_panel.add(stores_panel);
        parent_panel.repaint();
        parent_panel.revalidate();
    }//GEN-LAST:event_stores_button_panelMouseClicked

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        LoginScreen ls = new LoginScreen();
        ls.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    private void sell_tickets_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_tickets_buttonActionPerformed

        String product_name = "Ticket";
        String store = "";
        String Fair = fair_name_label.getText();
        double selling_price = getCurrentFair(fair_name_label.getText()).getEntry_fee();
        double cost_price = 0;
        double profit = selling_price - cost_price;
        String category = "";
        int quantity = 0;
        int num_sold = (int)num_people_spinner.getValue();

        Product ticket = new Product(product_name,store,Fair,selling_price,cost_price,profit,category,quantity,num_sold);
        System.out.println(ticket.toString());
        LocalDate date = LocalDate.now();

        Sale s = new Sale(ticket,store,Fair,date,profit);
        System.out.println(s.toString());
        try {
            sales_manager.addSale(s);
        } catch (SQLException ex) {
            Logger.getLogger(FairManagerScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_sell_tickets_buttonActionPerformed

    private void num_people_spinnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num_people_spinnerMouseClicked
        int num_people = (int)num_people_spinner.getValue();
        double entrance_cost = getCurrentFair(fair_name_label.getText()).getEntry_fee();
        double total = num_people * entrance_cost;
        ticket_total_price_field.setText("" + total);
    }//GEN-LAST:event_num_people_spinnerMouseClicked

    private void num_people_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_num_people_spinnerStateChanged
        int num_people = (int)num_people_spinner.getValue();
        double entrance_cost = getCurrentFair(fair_name_label.getText()).getEntry_fee();
        double total = num_people * entrance_cost;
        ticket_total_price_field.setText("" + total);
    }//GEN-LAST:event_num_people_spinnerStateChanged

    private void entrance_button_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrance_button_panelMouseClicked

        //changes colour of panels and labels to show a tab is selected
        changeBackgroundColor(entrance_button_panel, current_button,entrance_management_label,current_label);
        current_button = entrance_button_panel;
        current_label = entrance_management_label;
        try {
            initialiseTicketSalesTable(Ticket_sales_table);
        } catch (SQLException ex) {
            Logger.getLogger(FairManagerScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        //changes the card layout to bring up the dashboard panel
        parent_panel.removeAll();
        parent_panel.add(entrance_management_panel);
        parent_panel.repaint();
        parent_panel.revalidate();
    }//GEN-LAST:event_entrance_button_panelMouseClicked

    private Fair getCurrentFair(String fair_name){
        return fm.searchStore(fair_name);
    }
    
    private void setCustomFont(JLabel label){
        
    try {

    Font customFont = Font.createFont(Font.TRUETYPE_FONT, new File("AmbarPearlPersonalUse-0nBz.ttf")).deriveFont(30f);
    GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
    label.setFont(customFont);
    
        ge.registerFont(customFont);
    } catch (IOException e) {
        e.printStackTrace();
    } catch(FontFormatException e) {
        e.printStackTrace();
    }      
        
    }
    
    public void initialiseStoresOfFairTable(JTable t) throws SQLException{
        
        String fair_name = fair_name_label.getText();
        ArrayList<Store> arr = sm.getListOfStoresByFair(fair_name_label.getText());
        String [] column_names = {"Store Name", "Profit","Customers Served","Category","Fair","Owner Username"};
        
        String [][] data = new String[100][6];
        
        for(int row_number = 0; row_number < arr.size() ; row_number++){
            
            data[row_number][0] = arr.get(row_number).getStore_name();
            data[row_number][1] = Double.toString(arr.get(row_number).getProfit());
            data[row_number][2] = Integer.toString(arr.get(row_number).getCustomersServed());
            data[row_number][3] = arr.get(row_number).getCategory();
            data[row_number][4] = arr.get(row_number).getFair_name();
            data[row_number][5] = arr.get(row_number).getOwner_name();
            
            
        }
        
        DefaultTableModel tm = new DefaultTableModel(data,column_names);
        t.setModel(tm);
        
    }
    
    public void initialiseTicketSalesTable(JTable t) throws SQLException{
        
        
        String fair_name = fair_name_label.getText();
        ArrayList<Sale> arr = sales_manager.getListOfTicketsByFair(fair_name_label.getText());
        
        
        String [] column_names = {"Item","Fair","Date","Proft"};
        
        String [][] data = new String[100][4];
        
        for(int row_number = 0; row_number < arr.size() ; row_number++){
            
            data[row_number][0] = arr.get(row_number).getProduct_sold().getProductName();
            data[row_number][1] = arr.get(row_number).getFair_name();
            data[row_number][2] = arr.get(row_number).getDate_of_sale().toString();
            data[row_number][3] = Double.toString(arr.get(row_number).getProfit());
            
            
        }
        
        DefaultTableModel tm = new DefaultTableModel(data,column_names);
        t.setModel(tm);
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ticket_sales_table;
    private javax.swing.JButton back_button;
    private javax.swing.JPanel entrance_button_panel;
    private javax.swing.JLabel entrance_management_label;
    private javax.swing.JPanel entrance_management_panel;
    public javax.swing.JLabel fair_name_label;
    private javax.swing.JPanel fair_statistics_button_panel;
    private javax.swing.JLabel fair_statistics_label;
    private javax.swing.JPanel fair_statistics_panel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField least_popular_store_field;
    private javax.swing.JTextField most_popular_store_field;
    public javax.swing.JLabel my_fair_lady_label;
    private javax.swing.JSpinner num_people_spinner;
    private javax.swing.JPanel panel_left;
    private javax.swing.JPanel panel_middle;
    private javax.swing.JPanel parent_panel;
    private javax.swing.JButton sell_tickets_button;
    private javax.swing.JPanel stores_button_panel;
    private javax.swing.JLabel stores_label;
    private javax.swing.JTable stores_of_fair_table;
    private javax.swing.JPanel stores_panel;
    private javax.swing.JTextField ticket_total_price_field;
    private javax.swing.JTextField total_profit_of_fair;
    private javax.swing.JLabel user_management_screen_label;
    private javax.swing.JLabel user_management_screen_label1;
    private javax.swing.JLabel user_management_screen_label2;
    // End of variables declaration//GEN-END:variables
}
