/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Panel;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Neeraav Ranjit
 */
public class store_manager_dashboard extends javax.swing.JFrame {
//
    private JPanel current_button;
    private JLabel current_label;
    /**
     * Creates new form store_manager_dashboard
     */
    public store_manager_dashboard() {
        initComponents();
        
        setCustomFont(logo_label1);
        setCustomFont(logo_label2);
        
        current_button = dashboard_button_panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_left = new javax.swing.JPanel();
        dashboard_button_panel = new javax.swing.JPanel();
        dashboard_label = new javax.swing.JLabel();
        sales_button_panel = new javax.swing.JPanel();
        sales_label = new javax.swing.JLabel();
        inventory_button_panel = new javax.swing.JPanel();
        inventory_label = new javax.swing.JLabel();
        statistics_button_panel = new javax.swing.JPanel();
        statistics_label = new javax.swing.JLabel();
        logo_label = new javax.swing.JLabel();
        panel_right = new javax.swing.JPanel();
        sales_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inventory_panel = new javax.swing.JPanel();
        logo_label2 = new javax.swing.JLabel();
        statistics_panel = new javax.swing.JPanel();
        logo_label1 = new javax.swing.JLabel();
        panel_middle = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(65, 67, 106));

        panel_left.setBackground(new java.awt.Color(152, 64, 99));

        dashboard_button_panel.setBackground(new java.awt.Color(254, 150, 103));
        dashboard_button_panel.setPreferredSize(new java.awt.Dimension(100, 50));
        dashboard_button_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboard_button_panelMouseClicked(evt);
            }
        });

        dashboard_label.setBackground(new java.awt.Color(254, 150, 103));
        dashboard_label.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        dashboard_label.setForeground(new java.awt.Color(255, 255, 255));
        dashboard_label.setText("DASHBOARD");

        javax.swing.GroupLayout dashboard_button_panelLayout = new javax.swing.GroupLayout(dashboard_button_panel);
        dashboard_button_panel.setLayout(dashboard_button_panelLayout);
        dashboard_button_panelLayout.setHorizontalGroup(
            dashboard_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard_button_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboard_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboard_button_panelLayout.setVerticalGroup(
            dashboard_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboard_button_panelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(dashboard_label)
                .addGap(16, 16, 16))
        );

        sales_button_panel.setBackground(new java.awt.Color(65, 67, 106));
        sales_button_panel.setPreferredSize(new java.awt.Dimension(100, 50));
        sales_button_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sales_button_panelMouseClicked(evt);
            }
        });

        sales_label.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        sales_label.setForeground(new java.awt.Color(254, 150, 103));
        sales_label.setText("SALES");

        javax.swing.GroupLayout sales_button_panelLayout = new javax.swing.GroupLayout(sales_button_panel);
        sales_button_panel.setLayout(sales_button_panelLayout);
        sales_button_panelLayout.setHorizontalGroup(
            sales_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sales_button_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sales_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sales_button_panelLayout.setVerticalGroup(
            sales_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sales_button_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(sales_label)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        inventory_button_panel.setBackground(new java.awt.Color(65, 67, 106));
        inventory_button_panel.setPreferredSize(new java.awt.Dimension(100, 50));
        inventory_button_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventory_button_panelMouseClicked(evt);
            }
        });

        inventory_label.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        inventory_label.setForeground(new java.awt.Color(254, 150, 103));
        inventory_label.setText("INVENTORY");

        javax.swing.GroupLayout inventory_button_panelLayout = new javax.swing.GroupLayout(inventory_button_panel);
        inventory_button_panel.setLayout(inventory_button_panelLayout);
        inventory_button_panelLayout.setHorizontalGroup(
            inventory_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
            .addGroup(inventory_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inventory_button_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(inventory_label)
                    .addContainerGap(240, Short.MAX_VALUE)))
        );
        inventory_button_panelLayout.setVerticalGroup(
            inventory_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(inventory_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inventory_button_panelLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(inventory_label)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        statistics_button_panel.setBackground(new java.awt.Color(65, 67, 106));
        statistics_button_panel.setPreferredSize(new java.awt.Dimension(100, 50));
        statistics_button_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statistics_button_panelMouseClicked(evt);
            }
        });

        statistics_label.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        statistics_label.setForeground(new java.awt.Color(254, 150, 103));
        statistics_label.setText("STATISTICS");

        javax.swing.GroupLayout statistics_button_panelLayout = new javax.swing.GroupLayout(statistics_button_panel);
        statistics_button_panel.setLayout(statistics_button_panelLayout);
        statistics_button_panelLayout.setHorizontalGroup(
            statistics_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
            .addGroup(statistics_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(statistics_button_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(statistics_label)
                    .addContainerGap(244, Short.MAX_VALUE)))
        );
        statistics_button_panelLayout.setVerticalGroup(
            statistics_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(statistics_button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(statistics_button_panelLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(statistics_label)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        try{
            Font font = Font.createFont(Font.TRUETYPE_FONT,
                new File("AmbarPearlPersonalUse-0nBz.ttf"));
            Font bold = font.deriveFont(Font.BOLD, 12);
            Font plain = font.deriveFont(Font.PLAIN, 24);
            logo_label.setForeground(new java.awt.Color(254, 150, 103));
            logo_label.setFont(plain);
            logo_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            logo_label.setText("MyFairLady");
            logo_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        } catch (FontFormatException | IOException e){
            e.printStackTrace();
        }

        javax.swing.GroupLayout panel_leftLayout = new javax.swing.GroupLayout(panel_left);
        panel_left.setLayout(panel_leftLayout);
        panel_leftLayout.setHorizontalGroup(
            panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard_button_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(sales_button_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(inventory_button_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(statistics_button_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(logo_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_leftLayout.setVerticalGroup(
            panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_leftLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dashboard_button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sales_button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventory_button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statistics_button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_right.setBackground(new java.awt.Color(246, 70, 104));
        panel_right.setLayout(new java.awt.CardLayout());

        sales_panel.setBackground(new java.awt.Color(246, 70, 104));

        jLabel1.setText("Sales");

        javax.swing.GroupLayout sales_panelLayout = new javax.swing.GroupLayout(sales_panel);
        sales_panel.setLayout(sales_panelLayout);
        sales_panelLayout.setHorizontalGroup(
            sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sales_panelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        sales_panelLayout.setVerticalGroup(
            sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sales_panelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(442, Short.MAX_VALUE))
        );

        panel_right.add(sales_panel, "card2");

        inventory_panel.setBackground(new java.awt.Color(246, 70, 104));

        try{
            Font font = Font.createFont(Font.TRUETYPE_FONT,
                new File("AmbarPearlPersonalUse-0nBz.ttf"));
            Font bold = font.deriveFont(Font.BOLD, 12);
            Font plain = font.deriveFont(Font.PLAIN, 24);
            logo_label2.setForeground(new java.awt.Color(254, 150, 103));
            logo_label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            logo_label2.setText("Inventory");
            logo_label2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        } catch (FontFormatException | IOException e){
            e.printStackTrace();
        }

        javax.swing.GroupLayout inventory_panelLayout = new javax.swing.GroupLayout(inventory_panel);
        inventory_panel.setLayout(inventory_panelLayout);
        inventory_panelLayout.setHorizontalGroup(
            inventory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventory_panelLayout.createSequentialGroup()
                .addComponent(logo_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 149, Short.MAX_VALUE))
        );
        inventory_panelLayout.setVerticalGroup(
            inventory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventory_panelLayout.createSequentialGroup()
                .addComponent(logo_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 515, Short.MAX_VALUE))
        );

        panel_right.add(inventory_panel, "card3");

        statistics_panel.setBackground(new java.awt.Color(246, 70, 104));

        try{
            Font font = Font.createFont(Font.TRUETYPE_FONT,
                new File("AmbarPearlPersonalUse-0nBz.ttf"));
            Font bold = font.deriveFont(Font.BOLD, 12);
            Font plain = font.deriveFont(Font.PLAIN, 24);
            logo_label1.setForeground(new java.awt.Color(254, 150, 103));
            logo_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            logo_label1.setText("Statistics");
            logo_label1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        } catch (FontFormatException | IOException e){
            e.printStackTrace();
        }

        javax.swing.GroupLayout statistics_panelLayout = new javax.swing.GroupLayout(statistics_panel);
        statistics_panel.setLayout(statistics_panelLayout);
        statistics_panelLayout.setHorizontalGroup(
            statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statistics_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        statistics_panelLayout.setVerticalGroup(
            statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statistics_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logo_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(493, Short.MAX_VALUE))
        );

        panel_right.add(statistics_panel, "card4");

        panel_middle.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout panel_middleLayout = new javax.swing.GroupLayout(panel_middle);
        panel_middle.setLayout(panel_middleLayout);
        panel_middleLayout.setHorizontalGroup(
            panel_middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        panel_middleLayout.setVerticalGroup(
            panel_middleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_middle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_middle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setCustomFont(JLabel label){
        
    try {

    Font customFont = Font.createFont(Font.TRUETYPE_FONT, new File("AmbarPearlPersonalUse-0nBz.ttf")).deriveFont(12f);
    GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
    label.setFont(customFont);
    
        ge.registerFont(customFont);
    } catch (IOException e) {
        e.printStackTrace();
    } catch(FontFormatException e) {
        e.printStackTrace();
    }      
        
    }
    
    private void changeBackgroundColor(JPanel newP, JPanel old){
        Color off = new Color(65,67,106);
        Color on = new Color(254,150,103);
        Color label_off = new Color(254,150,103);
        Color label_on = new Color(255,255,255);
//        newP.setBackground(on);
//        oldP.setBackground(off);
//        newL.setForeground(label_on);
//        oldL.setForeground(label_off);
    }
    
    
    private void sales_button_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sales_button_panelMouseClicked
        
//        sales_button_panel.setBackground(254,150,103);
         changeBackgroundColor(sales_button_panel, current_button);
        current_button = sales_button_panel;
        panel_right.removeAll();
        panel_right.add(sales_panel);
        panel_right.repaint();
        panel_right.revalidate();
       
    }//GEN-LAST:event_sales_button_panelMouseClicked

    private void inventory_button_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventory_button_panelMouseClicked
         changeBackgroundColor(inventory_button_panel, current_button);
        current_button = inventory_button_panel;
        panel_right.removeAll();
        panel_right.add(inventory_panel);
        panel_right.repaint();
        panel_right.revalidate();
    }//GEN-LAST:event_inventory_button_panelMouseClicked

    private void statistics_button_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statistics_button_panelMouseClicked
                 changeBackgroundColor(statistics_button_panel, current_button);
        current_button = statistics_button_panel;
        panel_right.removeAll();
        panel_right.add(statistics_panel);
        panel_right.repaint();
        panel_right.revalidate();
    }//GEN-LAST:event_statistics_button_panelMouseClicked

    private void dashboard_button_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_button_panelMouseClicked
        changeBackgroundColor(dashboard_button_panel, current_button);
        current_button = dashboard_button_panel;
        
    }//GEN-LAST:event_dashboard_button_panelMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(store_manager_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(store_manager_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(store_manager_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(store_manager_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new store_manager_dashboard().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashboard_button_panel;
    private javax.swing.JLabel dashboard_label;
    private javax.swing.JPanel inventory_button_panel;
    private javax.swing.JLabel inventory_label;
    private javax.swing.JPanel inventory_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo_label;
    private javax.swing.JLabel logo_label1;
    private javax.swing.JLabel logo_label2;
    private javax.swing.JPanel panel_left;
    private javax.swing.JPanel panel_middle;
    private javax.swing.JPanel panel_right;
    private javax.swing.JPanel sales_button_panel;
    private javax.swing.JLabel sales_label;
    private javax.swing.JPanel sales_panel;
    private javax.swing.JPanel statistics_button_panel;
    private javax.swing.JLabel statistics_label;
    private javax.swing.JPanel statistics_panel;
    // End of variables declaration//GEN-END:variables
}
